version: '3.8'

services:
  album-viewer-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ospotemou?characterEncoding=latin1&useConfigs=maxPerformance
       SPRING_DATASOURCE_USERNAME : root
       SPRING_DATASOURCE_PASSWORD: root
       SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
       SPOTIFY_API_TOKEN : BQAvm_bf7aw47FDzpPVUvmQ_oXSArMPFO88tBrPCk-rheE-rXWOOGt8nn4_bqci5NI9srtSIFweIJzD0lkTmPtcGojRTd8maHt8Bqsw1VUhH-DXHNCY
    depends_on:
      - db
    restart: unless-stopped

  db:
    build: docker-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
