version: '3.8'

services:
  album-viewer-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ospotemou?characterEncoding=latin1&useConfigs=maxPerformance
       SPRING_DATASOURCE_USERNAME : root
       SPRING_DATASOURCE_PASSWORD: root
       SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
       SPOTIFY_API_TOKEN : BQBzNxb1Sy8-JaYZCL9X5kbStUeG-ub7UJ4A0dAxpJGyR8TGob3Rs1468Bc7WmC5_QS8UTEUbn7BI-luDmEngp5zgdtc44Tszf-08PyryRI3zZdUwFs
    depends_on:
      - db
    restart: unless-stopped

  db:
    build: docker-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
